<?php
namespace Application\Entity;

use Doctrine\ORM\EntityRepository;

class FuncaoRepository extends EntityRepository
{
    public function findAll()
    {
        return parent::findBy(array(), array('nome' => 'ASC')); // TODO: Change the autogenerated stub
    }
}
