<?php
namespace Application\Entity;

use Doctrine\ORM\EntityRepository;

class ParticipanteRepository extends EntityRepository
{

    public function findAll()
    {
        return parent::findBy(array(), array('nomeCompleto' => 'ASC')); // TODO: Change the autogenerated stub
    }

    function findByCpfDataNascimento($cpf, $data_nascimento)
    {
        $participante = $this->findOneBy(array(
            'cpf' => $cpf,
            'dataNascimento' => $data_nascimento
        ));
        
        if (! is_null($participante)) {
            return $participante;
        }
        
        return false;
    }
}
