<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Atividade extends \Application\Entity\Atividade implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\Atividade' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Atividade' . "\0" . 'cargaHoraria', '' . "\0" . 'Application\\Entity\\Atividade' . "\0" . 'titulo', '' . "\0" . 'Application\\Entity\\Atividade' . "\0" . 'dataInicio', '' . "\0" . 'Application\\Entity\\Atividade' . "\0" . 'dataFim', '' . "\0" . 'Application\\Entity\\Atividade' . "\0" . 'evento', '' . "\0" . 'Application\\Entity\\Atividade' . "\0" . 'tipoAtividade'];
        }

        return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\Atividade' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Atividade' . "\0" . 'cargaHoraria', '' . "\0" . 'Application\\Entity\\Atividade' . "\0" . 'titulo', '' . "\0" . 'Application\\Entity\\Atividade' . "\0" . 'dataInicio', '' . "\0" . 'Application\\Entity\\Atividade' . "\0" . 'dataFim', '' . "\0" . 'Application\\Entity\\Atividade' . "\0" . 'evento', '' . "\0" . 'Application\\Entity\\Atividade' . "\0" . 'tipoAtividade'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Atividade $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function dataForm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'dataForm', []);

        return parent::dataForm();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getCargaHoraria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCargaHoraria', []);

        return parent::getCargaHoraria();
    }

    /**
     * {@inheritDoc}
     */
    public function setCargaHoraria($cargaHoraria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCargaHoraria', [$cargaHoraria]);

        return parent::setCargaHoraria($cargaHoraria);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoAtividade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoAtividade', []);

        return parent::getTipoAtividade();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoAtividade($tipoAtividade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoAtividade', [$tipoAtividade]);

        return parent::setTipoAtividade($tipoAtividade);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', []);

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo($titulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', [$titulo]);

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getEvento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvento', []);

        return parent::getEvento();
    }

    /**
     * {@inheritDoc}
     */
    public function setEvento($evento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEvento', [$evento]);

        return parent::setEvento($evento);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataInicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataInicio', []);

        return parent::getDataInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataInicio($dataInicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataInicio', [$dataInicio]);

        return parent::setDataInicio($dataInicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataFim()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataFim', []);

        return parent::getDataFim();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataFim($dataFim)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataFim', [$dataFim]);

        return parent::setDataFim($dataFim);
    }

}
