<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Evento extends \Application\Entity\Evento implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'nome', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'sigla', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'ano', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'numeroEdicao', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'dataFinal', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'dataInicial', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'usuario', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'atividades', 'verbose_name', 'verbose_name_plural'];
        }

        return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'nome', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'sigla', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'ano', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'numeroEdicao', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'dataFinal', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'dataInicial', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'usuario', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'atividades', 'verbose_name', 'verbose_name_plural'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Evento $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function dataForm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'dataForm', []);

        return parent::dataForm();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', []);

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', [$nome]);

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function getSigla()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSigla', []);

        return parent::getSigla();
    }

    /**
     * {@inheritDoc}
     */
    public function setSigla($sigla)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSigla', [$sigla]);

        return parent::setSigla($sigla);
    }

    /**
     * {@inheritDoc}
     */
    public function getAno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAno', []);

        return parent::getAno();
    }

    /**
     * {@inheritDoc}
     */
    public function setAno($ano)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAno', [$ano]);

        return parent::setAno($ano);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroEdicao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroEdicao', []);

        return parent::getNumeroEdicao();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroEdicao($numeroEdicao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroEdicao', [$numeroEdicao]);

        return parent::setNumeroEdicao($numeroEdicao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataFinal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataFinal', []);

        return parent::getDataFinal();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataFinal($dataFinal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataFinal', [$dataFinal]);

        return parent::setDataFinal($dataFinal);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataInicial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataInicial', []);

        return parent::getDataInicial();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataInicial($dataInicial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataInicial', [$dataInicial]);

        return parent::setDataInicial($dataInicial);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario($usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtividades()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtividades', []);

        return parent::getAtividades();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtividades($atividades)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtividades', [$atividades]);

        return parent::setAtividades($atividades);
    }

    /**
     * {@inheritDoc}
     */
    public function getTiposDeAtividades()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTiposDeAtividades', []);

        return parent::getTiposDeAtividades();
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriodo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriodo', []);

        return parent::getPeriodo();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataFormatada(\DateTime $data_inicio, \DateTime $data_fim)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataFormatada', [$data_inicio, $data_fim]);

        return parent::getDataFormatada($data_inicio, $data_fim);
    }

    /**
     * {@inheritDoc}
     */
    public function getMesExtenso($mes_numero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMesExtenso', [$mes_numero]);

        return parent::getMesExtenso($mes_numero);
    }

    /**
     * {@inheritDoc}
     */
    public function convert_number_to_words($number)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'convert_number_to_words', [$number]);

        return parent::convert_number_to_words($number);
    }

}
