<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Participante extends \Application\Entity\Participante implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\Participante' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Participante' . "\0" . 'cpf', '' . "\0" . 'Application\\Entity\\Participante' . "\0" . 'nomeCompleto', '' . "\0" . 'Application\\Entity\\Participante' . "\0" . 'dataNascimento', '' . "\0" . 'Application\\Entity\\Participante' . "\0" . 'email', '' . "\0" . 'Application\\Entity\\Participante' . "\0" . 'instituicaoIfbaVca', 'verbose_name', 'verbose_name_plural', '' . "\0" . 'Application\\Entity\\Participante' . "\0" . 'participacoes'];
        }

        return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\Participante' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Participante' . "\0" . 'cpf', '' . "\0" . 'Application\\Entity\\Participante' . "\0" . 'nomeCompleto', '' . "\0" . 'Application\\Entity\\Participante' . "\0" . 'dataNascimento', '' . "\0" . 'Application\\Entity\\Participante' . "\0" . 'email', '' . "\0" . 'Application\\Entity\\Participante' . "\0" . 'instituicaoIfbaVca', 'verbose_name', 'verbose_name_plural', '' . "\0" . 'Application\\Entity\\Participante' . "\0" . 'participacoes'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Participante $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function dataForm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'dataForm', []);

        return parent::dataForm();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getCpf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCpf', []);

        return parent::getCpf();
    }

    /**
     * {@inheritDoc}
     */
    public function setCpf($cpf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCpf', [$cpf]);

        return parent::setCpf($cpf);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomeCompleto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomeCompleto', []);

        return parent::getNomeCompleto();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomeCompleto($nomeCompleto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomeCompleto', [$nomeCompleto]);

        return parent::setNomeCompleto($nomeCompleto);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataNascimento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataNascimento', []);

        return parent::getDataNascimento();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataNascimento($dataNascimento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataNascimento', [$dataNascimento]);

        return parent::setDataNascimento($dataNascimento);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getInstituicao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInstituicao', []);

        return parent::getInstituicao();
    }

    /**
     * {@inheritDoc}
     */
    public function setInstituicao($instituicaoIfbaVca)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInstituicao', [$instituicaoIfbaVca]);

        return parent::setInstituicao($instituicaoIfbaVca);
    }

    /**
     * {@inheritDoc}
     */
    public function getInstituicaoIfbaVca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInstituicaoIfbaVca', []);

        return parent::getInstituicaoIfbaVca();
    }

    /**
     * {@inheritDoc}
     */
    public function setInstituicaoIfbaVca($instituicaoIfbaVca)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInstituicaoIfbaVca', [$instituicaoIfbaVca]);

        return parent::setInstituicaoIfbaVca($instituicaoIfbaVca);
    }

    /**
     * {@inheritDoc}
     */
    public function getParticipacoes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParticipacoes', []);

        return parent::getParticipacoes();
    }

    /**
     * {@inheritDoc}
     */
    public function setParticipacoes($participacoes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParticipacoes', [$participacoes]);

        return parent::setParticipacoes($participacoes);
    }

    /**
     * {@inheritDoc}
     */
    public function getVerboseName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVerboseName', []);

        return parent::getVerboseName();
    }

    /**
     * {@inheritDoc}
     */
    public function setVerboseName($verbose_name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVerboseName', [$verbose_name]);

        return parent::setVerboseName($verbose_name);
    }

}
