<?php
namespace Application\Service;

use Base\Service\AbstractService;
use Doctrine\ORM\EntityManager;

class Evento extends AbstractService
{

    public function __construct(EntityManager $em)
    {
        parent::__construct($em);
        
        $this->entity = 'Application\Entity\Evento';
        $this->errorCodeValidator = [
            1451 => 'Para excluir esse evento você deverá excluir todas as participações e atividades a ele vinculado'
        ];
    }

    public function insert($data)
    {
        $data['usuario'] = $this->em->getRepository('Application\Entity\Usuario')->find($data['usuario']);
        
        $data['data_inicial'] = substr($data['data_inicial'], 6, 4) . '-' . substr($data['data_inicial'], 3, 2) . '-' . substr($data['data_inicial'], 0, 2);
        
        $data['data_final'] = substr($data['data_final'], 6, 4) . '-' . substr($data['data_final'], 3, 2) . '-' . substr($data['data_final'], 0, 2);
        
        $datetime = new \DateTime($data['data_inicial']);
        $data['data_inicial'] = $datetime;
        
        $datetime = new \DateTime($data['data_final']);
        $data['data_final'] = $datetime;
        
        return parent::insert($data); // TODO: Change the autogenerated stub
    }

    public function update($data)
    {
        $data['usuario'] = $this->em->getRepository('Application\Entity\Usuario')->find($data['usuario']);
        
        $data['data_inicial'] = substr($data['data_inicial'], 6, 4) . '-' . substr($data['data_inicial'], 3, 2) . '-' . substr($data['data_inicial'], 0, 2);
        
        $data['data_final'] = substr($data['data_final'], 6, 4) . '-' . substr($data['data_final'], 3, 2) . '-' . substr($data['data_final'], 0, 2);
        
        $datetime = new \DateTime($data['data_inicial']);
        $data['data_inicial'] = $datetime;
        
        $datetime = new \DateTime($data['data_final']);
        $data['data_final'] = $datetime;
        
        return parent::update($data); // TODO: Change the autogenerated stub
    }
}

