<?php
/** @var  $row \Application\Entity\Evento */
$data = $this->data;
?>


<div class="portlet light">
	<div class="portlet-title">
		<div class="caption">
			<i class="fa fa-graduation-cap font-green" aria-hidden="true"></i> <span
				class="caption-subject font-green bold uppercase"> Eventos</span> <span
				class="caption-helper"></span>
		</div>
		<div class="actions">
			<a
				href="<?php echo $this->url('evento/default', array('action' => 'cadastrar'))?>"
				class="btn green border-white sbold"> <i class="fa fa-plus"></i>
				CADASTRAR EVENTO
			</a> <a class="btn  btn-icon-only btn-default fullscreen"
				href="javascript:;" data-original-title="" title=""> </a>
		</div>
	</div>
	<div class="portlet-body" style="height: auto;">
        <?php echo $this->partial('partial/messages');?>

        <table class="table table-hover table-light" id="sample_1">
			<thead>
				<tr>
					<th>Nome</th>
					<th>Sigla</th>
					<th>Ano</th>
					<th>Início</th>
					<th>Fim</th>
					<th>Coordenador</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
            <?php foreach($data as $row): ?>
                <tr>
					<td><?php echo $row->getNome(); ?></td>
					<td><?php echo $row->getSigla(); ?></td>
					<td><?php echo $row->getAno(); ?></td>
					<td><?php echo $row->getDataInicial()->format('d/m/Y'); ?></td>
					<td><?php echo $row->getDataFinal()->format('d/m/Y'); ?></td>
					<td><?php echo $row->getUsuario()->getLogin(); ?></td>

					<td style="text-align: right; width: 220px;">
						<div class="clearfix">
							<a
								href="<?php  echo $this->url('participacao/default', array('action' => 'cadastrar', 'evento' => $row->getId()));?>"
								class="btn btn-icon-only green-meadow"
								title="Cadastrar participação no evento"> <i class="fa fa-plus"
								aria-hidden="true"></i>
							</a> <a
								href="<?php  echo $this->url('evento/default', array('action' => 'editar', 'id' => $row->getId()));?>"
								class="btn btn-icon-only yellow-saffron" title="Editar"> <i
								class="fa fa-pencil" aria-hidden="true"></i>
							</a> <a
								href="<?php  echo $this->url('configurar-modelo-certificado/default', array('action' => 'cadastrar', 'evento' => $row->getId()));?>"
								class="btn btn-icon-only green"
								title="Modelo de certificado para <?php echo $row->getNome();?>">
								<i class="fa fa-certificate" aria-hidden="true"></i>
							</a> <a
								href="<?php  echo $this->url('evento/default', array('action' => 'deletar', 'id' => $row->getId()));?>"
								class="btn btn-icon-only red" title="Deletar evento"
								onclick="return confirm('Confirmar exclusão de evento ?');"> <i
								class="fa fa-trash" aria-hidden="true"></i>
							</a>


						</div>
					</td>
				</tr>
            <?php endforeach; ?>
        
		
		</table>
	</div>
</div>
