
<?php $evento = $this->evento;?>
<div class="portlet light">
	<div class="portlet-title">
		<div class="caption">

			<i class="fa fa-plus font-green" aria-hidden="true"></i> <span
				class="caption-subject font-green bold uppercase"> Cadastrar
				atividades do evento por planilha</span> <span
				class="caption-helper"> </span>
		</div>
		<div class="actions">

			<div class="btn-group">
				<a class="btn  green btn-sm" href="javascript:;"
					data-toggle="dropdown" data-hover="dropdown"
					data-close-others="true"> Menu <i class="fa fa-angle-down"></i>
				</a>
				<ul class="dropdown-menu pull-right">
					<li><a
						href="<?php echo $this->url('participacao/default', array('action' => 'cadastrar', 'evento' => $evento->getId()))?>">
							<i class="i"></i> Participações
					</a></li>
					<li><a
						href="<?php echo $this->url('cadastrar-atividades-por-planilha', array('evento' => $evento->getId()))?>">
							<i class="i"></i> Atividades por planilha
					</a></li>
					<li><a
						href="<?php echo $this->url('atividade/default', array('action' => 'cadastrar', 'evento' => $evento->getId()))?>">
							<i class="i"></i> Atividades
					</a></li>

                    <li><a
                                href="<?php echo $this->url('modelo-certificado/default', array('action' => 'cadastrar', 'evento' => $evento->getId()))?>">
                            <i class="i"></i> Modelo de certificados
                        </a></li>

				</ul>
			</div>
			<a class="btn  btn-icon-only btn-default fullscreen"
				href="javascript:;" data-original-title="" title=""> </a>
		</div>
	</div>

	<div class="portlet-body">
		<div class="portlet-title padding-tb-15">
			<h5 class="caption-subject font-green-dark sbold uppercase">Evento:</h5>
			<h5 class="caption-subject font-dark sbold uppercase"><?php echo $evento; ?></h5>
		</div>
		<div class="note note-info">
			<h4 class="block">Atenção</h4>
			<p>É obrigatório informar os seguintes campos: Nome da atividade,
				Carga horária, Tipo, Data início e Data fim. Na ausência de um
				desses campos o cadastro das atividades não será realizado.</p>
		</div>

		<div style="padding: 0 0 30px 0;">
			<a
				href="<?php echo $this->url('publico/default', array('action' => 'download-cadastrar-atividades-do-evento-por-planilha'));?>"
				class="btn btn blue" id="blockui_sample_1_3"> <i
				class="fa fa-download"></i> Baixar planilha de exemplo
			</a>
		</div>

        <?php echo $this->partial('partial/messages');?>


        <?php
        if ($this->formElementErrors($form->get('planilha')))
            echo $this->formElementErrors()
                ->setMessageOpenFormat('<div class="note note-danger" style="margin-bottom: 10px">')
                ->setMessageSeparatorString('</div><div class="note note-danger" style="margin-bottom: 10px">')
                ->setMessageCloseString('</div>')
                ->render($form->get('planilha'));
        ?>

        <div class="portlet light bordered "
			style="background: #f5f5f5;">
			<div class="portlet-body">
                <?php $form = $this->form; ?>
                <?php $form->prepare(); ?>
                <?php echo $this->form()->openTag($form); ?>
                <?php echo $this->formElement($form->get('evento')); ?>
                <div class="form-group">
					<label class="sr-only" for="exampleInputEmail2">Email address</label>
                    <?php echo $this->formElement($form->get('planilha')); ?>
                </div>

			</div>

		</div>
	</div>

	<div class="form-actions">
		<div class="row">
			<div class="col-md-12">
				<button type="submit" class="btn btn green-jungle pull-right"
					id="blockui_sample_1_3">
					<i class="fa fa-send-o "></i> Enviar planilha
				</button>
			</div>
		</div>
	</div>
    <?php echo $this->form()->closeTag($form); ?>
</div>
</div>
