<?php
/** @var  $row \Application\Entity\ModeloCertificado */
$data = $this->data;
?>


<div class="portlet light">
	<div class="portlet-title">
		<div class="caption">
			<i class="fa fa-certificate font-green" aria-hidden="true"></i> <span
				class="caption-subject font-green bold uppercase"> Modelos
				certificados:</span> <span class="caption-helper"></span>
		</div>
		<div class="actions">
			<a
				href="<?php echo $this->url('modelo-certificado/default', array('action' => 'cadastrar'))?>"
				class="btn green border-white sbold"> <i class="fa fa-plus"></i>
				CADASTRAR MODELO
			</a> <a class="btn  btn-icon-only btn-default fullscreen"
				href="javascript:;" data-original-title="" title=""> </a>
		</div>
	</div>
	<div class="portlet-body" style="height: auto;">
        <?php echo $this->partial('partial/messages');?>

        <table class="table table-hover table-light" id="sample_1">
			<thead>
				<tr>
                    <th style="width: 150px;">Frente</th>
                    <th>Nome</th>
                    <th></th>
				</tr>
			</thead>
			<tbody>
            <?php foreach($data as $row): ?>
                <tr>
                    <td>
                        <img id="img-bg-frente" src="/assets/certificados/frente/<?php echo $row->getBgFrente(); ?>" style=" width: 130PX ;height: auto; display: block;"/>
                    </td>
					<td><?php echo $row->getNome(); ?></td>
					<td style="text-align: right; width: 137px;">
						<div class="clearfix">

							<a
								href="<?php  echo $this->url('modelo-certificado/default', array('action' => 'detalhes', 'id' => $row->getId()));?>"
								class="btn btn-icon-only blue-sharp" title="Detalhes"> <i
								class="fa fa-info" aria-hidden="true"></i>
							</a> <a
								href="<?php  echo $this->url('modelo-certificado/default', array('action' => 'editar', 'id' => $row->getId()));?>"
								class="btn btn-icon-only yellow-saffron" title="Editar"> <i
								class="fa fa-pencil" aria-hidden="true"></i>
							</a>

                            <a href="<?php
                            echo $this->url('modelo-certificado/default',
                                array('action' => 'deletar', 'id' => $row->getId())
                            );?>"
                                    class="btn btn-icon-only red" title="Deletar modelo do certificado"
                                    onclick="return confirm('Confirmar exclusão de certificado <?php echo $row->getNome(); ?> ?');">
                                <i class="fa fa-trash" aria-hidden="true"></i>
                            </a>
						</div>
					</td>
				</tr>
            <?php endforeach; ?>
        
		
		</table>
	</div>
</div>
