<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="pt-BR">
<!--<![endif]-->
<!-- BEGIN HEAD -->

<head>
<meta charset="utf-8" />
<title>IFBA - Instituto Federal da Bahia</title>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="width=device-width, initial-scale=1" name="viewport" />
<meta content="" name="description" />
<meta content="Joabe Pinheiro" name="author" />
<!-- BEGIN GLOBAL MANDATORY STYLES -->
<link
	href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all"
	rel="stylesheet" type="text/css" />
<link
	href="/assets/global/plugins/font-awesome/css/font-awesome.min.css"
	rel="stylesheet" type="text/css" />
<link
	href="/assets/global/plugins/simple-line-icons/simple-line-icons.min.css"
	rel="stylesheet" type="text/css" />
<link href="/assets/global/plugins/bootstrap/css/bootstrap.min.css"
	rel="stylesheet" type="text/css" />
<link href="/assets/global/plugins/uniform/css/uniform.default.css"
	rel="stylesheet" type="text/css" />
<link
	href="/assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css"
	rel="stylesheet" type="text/css" />
<!-- END GLOBAL MANDATORY STYLES -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<link href="/assets/global/plugins/select2/css/select2.min.css"
	rel="stylesheet" type="text/css" />
<link
	href="/assets/global/plugins/select2/css/select2-bootstrap.min.css"
	rel="stylesheet" type="text/css" />
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN THEME GLOBAL STYLES -->
<link href="/assets/global/css/components.min.css" rel="stylesheet"
	id="style_components" type="text/css" />
<link href="/assets/global/css/plugins.min.css" rel="stylesheet"
	type="text/css" />
<!-- END THEME GLOBAL STYLES -->
<!-- BEGIN PAGE LEVEL STYLES -->
<link href="/assets/pages/css/login-3.min.css" rel="stylesheet"
	type="text/css" />
<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN THEME LAYOUT STYLES -->
<!-- END THEME LAYOUT STYLES -->
<link rel="shortcut icon" href="img/favicon.ico" />
</head>
<!-- END HEAD -->

<body class=" login" style="background: #fff !important;">

	<!-- BEGIN LOGIN -->
	<div class="content" style="margin-top: 40px">
		<!-- BEGIN LOGO -->
		<div style="padding: 20px 0">
			<a href="index.html"> <img src="/assets/layouts/layout4/img/logo.png"
				alt="" class="center-block" />
			</a>
		</div>
		<!-- END LOGO -->

    <?php if($this->menssages):?>
        <div
			class="alert alert-danger alert-bold-border fade in alert-dismissable">
			<button type="button" class="close" data-dismiss="alert"
				aria-hidden="true">&times;</button>
            <?php echo $this->menssages; ?>
        </div>
    <?php endif; ?>

    <!-- BEGIN LOGIN FORM -->
    <?php echo $this->form()->openTag($form) ?>

    <h3 class="form-title"></h3>
		<div class="alert alert-danger display-hide">
			<button class="close" data-close="alert"></button>
			<span> Enter any username and password. </span>
		</div>
		<div
			class="form-group <?php if($this->formElementErrors($form->get('cpf'))) echo " has-error" ?>">
			<!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
			<label class="control-label visible-ie8 visible-ie9">Username</label>

        <?php echo $this->formElement($form->get('cpf')); ?>

        <?php
        if ($this->formElementErrors($form->get('cpf')))
            echo $this->formElementErrors()
                ->setMessageOpenFormat('<small data-bv-validator="notEmpty" class="help-block" style="">')
                ->setMessageSeparatorString('</small><small data-bv-validator="notEmpty" class="help-block" style="">')
                ->setMessageCloseString('</small>')
                ->render($form->get('cpf'));
        ?>

    </div>
		<div
			class="form-group <?php if($this->formElementErrors($form->get('data_nascimento'))) echo " has-error" ?>">
			<label class="control-label visible-ie8 visible-ie9">Data de
				nascimento</label>

        <?php echo $this->formElement($form->get('data_nascimento')); ?>

        <?php
        if ($this->formElementErrors($form->get('data_nascimento')))
            echo $this->formElementErrors()
                ->setMessageOpenFormat('<small data-bv-validator="notEmpty" class="help-block" style="">')
                ->setMessageSeparatorString('</small><small data-bv-validator="notEmpty" class="help-block" style="">')
                ->setMessageCloseString('</small>')
                ->render($form->get('data_nascimento'));
        ?>

    </div>

		<div class="form-actions" style="border-bottom: 0;">
			<button type="submit" class="btn green btn-block"
				style="padding: 8px 0;">Entrar</button>
		</div>

		<!-- END LOGIN FORM -->
	</div>
	<!-- END LOGIN -->
	<!--[if lt IE 9]>
<script src="/assets/global/plugins/respond.min.js"></script>
<script src="/assets/global/plugins/excanvas.min.js"></script>
<![endif]-->
	<!-- BEGIN CORE PLUGINS -->
	<script src="/assets/global/plugins/jquery.min.js"
		type="text/javascript"></script>
	<script src="/assets/global/plugins/bootstrap/js/bootstrap.min.js"
		type="text/javascript"></script>
	<script src="/assets/global/plugins/js.cookie.min.js"
		type="text/javascript"></script>
	<script
		src="/assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js"
		type="text/javascript"></script>
	<script
		src="/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js"
		type="text/javascript"></script>
	<script src="/assets/global/plugins/jquery.blockui.min.js"
		type="text/javascript"></script>
	<script src="/assets/global/plugins/uniform/jquery.uniform.min.js"
		type="text/javascript"></script>
	<script
		src="/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js"
		type="text/javascript"></script>
	<!-- END CORE PLUGINS -->
	<!-- BEGIN PAGE LEVEL PLUGINS -->
	<script
		src="/assets/global/plugins/jquery-inputmask/jquery.inputmask.bundle.min.js"
		type="text/javascript"></script>
	<script
		src="/assets/global/plugins/jquery.input-ip-address-control-1.0.min.js"
		type="text/javascript"></script>

	<script
		src="/assets/global/plugins/jquery-validation/js/jquery.validate.min.js"
		type="text/javascript"></script>
	<script
		src="/assets/global/plugins/jquery-validation/js/additional-methods.min.js"
		type="text/javascript"></script>
	<script src="/assets/global/plugins/select2/js/select2.full.min.js"
		type="text/javascript"></script>
	<!-- END PAGE LEVEL PLUGINS -->
	<!-- BEGIN THEME GLOBAL SCRIPTS -->
	<script src="/assets/global/scripts/app.min.js" type="text/javascript"></script>
	<!-- END THEME GLOBAL SCRIPTS -->
	<!-- BEGIN PAGE LEVEL SCRIPTS -->
	<script src="/assets/pages/scripts/login.min.js" type="text/javascript"></script>
	<!-- END PAGE LEVEL SCRIPTS -->
	<!-- BEGIN THEME LAYOUT SCRIPTS -->
	<script src="/assets/pages/scripts/form-input-mask.js"
		type="text/javascript"></script>
	<!-- END THEME LAYOUT SCRIPTS -->

	<script type="text/javascript">
    $(document).ready(function() {
        $("#cpf").inputmask({
            "mask": "999.999.999-99"
        });

        $("#data_nascimento").inputmask({
            "mask": "99/99/9999"
        });
    });
</script>
</body>

</html>