<?php
/** @var  $modelo \Application\Entity\ModeloCertificado */
/** @var  $evento \Application\Entity\Evento */

$form = $this->form;
$evento = $this->evento;
$modelo = $this->modelo;
?>
<style>
    table span{
        background: transparent;
    }

    table input[type=text]{
        width: 230px;
    }
</style>


<div class="portlet light">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-certificate font-green" aria-hidden="true"></i>
            <span class="caption-subject font-green bold uppercase"> Alterar modelo do certificado para evento
			</span> <span class="caption-helper"></span>
        </div>
        <div class="actions">
            <?php echo $this->partial('evento/menu/superior', array(
                'evento' => $evento
            ));?>
            <a class="btn  btn-icon-only btn-default fullscreen"
               href="javascript:;" data-original-title="" title=""> </a>
        </div>
    </div>
    <div class="portlet-body" style="height: auto;">

        <?php echo $this->partial('evento/table/detalhes', array(
            'evento' => $evento
        ));?>

        <?php echo $this->partial('partial/messages');?>

        <?php echo $this->partial('modelo/tabela_tags_certificado');?>

        <?php $form->setAttribute('class', 'form-horizontal'); ?>
        <?php $form->prepare(); ?>

        <?php echo $this->form()->openTag($form); ?>
        <?php
        echo $this->partial('partial/form/general/quick/element/text', array(
            'element' => $form->get('nome'),
            'col_1' => 'col-md-2',
            'col_2' => 'col-md-9'
        ));
        ?>

        <?php
        echo $this->partial('partial/form/general/quick/element/select', array(
            'element' => $form->get('tipo'),
            'col_1' => 'col-md-2',
            'col_2' => 'col-md-9'
        ));
        ?>

        <div class="portlet light">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject font-dark sbold uppercase"> Dados da frente do certificado</span>
                </div>
            </div>
            <div class="portlet-body" style="height: auto;">

                <?php
                echo $this->partial('partial/form/general/quick/element/hidden', array(
                    'element' => $form->get('id')
                ));
                ?>

                <?php
                echo $this->partial('partial/form/general/quick/element/hidden', array(
                    'element' => $form->get('evento')
                ));
                ?>

                <?php
                echo $this->partial('partial/form/general/quick/element/textarea', array(
                    'element' => $form->get('texto_frente'),
                    'col_1' => 'col-md-2',
                    'col_2' => 'col-md-9'
                ));
                ?>

                <?php
                echo $this->partial('partial/form/general/quick/element/file', array(
                    'element' => $form->get('bgFrente'),
                    'col_1' => 'col-md-2',
                    'col_2' => 'col-md-9'
                ));
                ?>

                <div class="form-group ">
                    <label class="col-md-2 control-label">
                        Frente atual
                    </label>
                    <div class="col-md-9">
                        <img src="/assets/certificados/frente/<?php echo $modelo->getBgFrente(); ?>" class="img-responsive"/>
                    </div>
                </div>


            </div>
        </div>

        <div class="portlet light" id="container-verso" style="display: <?php echo ($modelo->getTipo() == 'frente') ? 'none' : 'block'; ?>">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject font-dark sbold uppercase"> Dados do verso do certificado</span>
                </div>
            </div>
            <div class="portlet-body" style="height: auto;">

                <?php
                echo $this->partial('partial/form/general/quick/element/textarea', array(
                    'element' => $form->get('texto_verso'),
                    'col_1' => 'col-md-2',
                    'col_2' => 'col-md-9'
                ));
                ?>

                <?php
                echo $this->partial('partial/form/general/quick/element/file', array(
                    'element' => $form->get('bgVerso'),
                    'col_1' => 'col-md-2',
                    'col_2' => 'col-md-9'
                ));
                ?>

                <div class="form-group ">
                    <label class="col-md-2 control-label">
                        Verso atual
                    </label>
                    <div class="col-md-9">
                        <?php if($modelo->getBgVerso() != null):?>
                        <img src="/assets/certificados/verso/<?php echo $modelo->getBgVerso(); ?>" class="img-responsive"/>
                        <?php else: ?>
                            Esse modelo não tem uma imagem para o verso
                        <?php endif; ?>
                    </div>
                </div>

            </div>
        </div>


        <div class="portlet light">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject font-dark sbold uppercase"> Críterios do modelo do certificado</span>
                </div>
                <div class="actions">
                    <button class="btn  btn-sm green add-criterio" type="button" title="adicionar novo critério">
                        <i class="fa fa-plus"></i>
                    </button>
                </div>
            </div>
            <div class="portlet-body" style="height: auto;">

                <div class="note note-info">
                    <p>Os critérios dos certificados indicam quais funções e atividades estão relacionadas ao modelo de certificado a ser cadastrado </p>
                </div>



                <table class="table table-bordered table-hover" id="tabela-criterios">
                    <thead>
                    <tr>
                        <td>Tipos de atividades</td>
                        <td>Funções</td>
                        <td></td>
                    </tr>
                    </thead>
                    <tbody>

                    <?php

                    /** @var  $certificadosTipoFuncaoEvento \Application\Entity\CertificadoTipoFuncaoEvento */
                    foreach ($modelo->getCertificadosTipoFuncaoEvento() as $certificadosTipoFuncaoEvento):  ?>
                    <tr class="opcao-criterio">
                        <td>
                            <?php
                            /** @var  $element_tipos_atividade \Zend\Form\Element\Select*/
                            $element_tipos_atividade = $form->get('tiposAtividade[]');
                            $element_tipos_atividade->setValue($certificadosTipoFuncaoEvento->getTipoAtividade()->getId());
                            $element_tipos_atividade->setAttribute('class', 'form-control ' .  $element_tipos_atividade->getAttribute('class'));
                            echo $this->formElement($element_tipos_atividade);
                            ?>
                        </td>
                        <td>
                            <?php
                            /** @var  $element_funcoes \Zend\Form\Element\Select*/
                            $element_funcoes = $form->get('funcoes[]');
                            $element_funcoes->setValue($certificadosTipoFuncaoEvento->getFuncao()->getId());
                            $element_funcoes->setAttribute('class', 'form-control ' .  $element_funcoes->getAttribute('class'));
                            echo $this->formElement($element_funcoes);
                            ?>
                        </td>
                        <td style="text-align: center;">

                            <button class="btn  btn-sm red remove-criterio" type="button" title="Remover criério do modelo">
                                <i class="fa fa-trash"></i>
                            </button>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>

        <?php
        echo $this->partial('partial/form/general/quick/element/submit', array(
            'element' => $form->get('submit'),
            'edit' => true
        ));
        ?>

        <?php echo $this->form()->closeTag($form); ?>


    </div>
</div>

<style type="text/css">
    #cke_editor1, #cke_editor2{
        display: none !important;
    }

    .ui-helper-hidden-accessible{
        display: none !important;
    }

    .note-editing-area{
        margin: 3px 0 !important;
    }
</style>

<script type="text/javascript">

    <?php $this->headScript()->captureStart() ?>

    var criterio = $( ".opcao-criterio" ).clone().first();
    criterio.find(".tiposAtividade option:selected").removeAttr('selected');
    criterio.find(".funcoes option:selected").removeAttr('selected');

    $( ".add-criterio" ).on( "click", function() {
        criterio.clone().prependTo( "#tabela-criterios tbody" );
    });

    $(document).on("click", ".remove-criterio" , function() {
        $(this).parent().parent().remove();
        validarCriteriosDoCertificado();
    });

    $(document).ready(function() {

        $("#modelo").change(function () {
            var modelo_value = $("#modelo").val();
            if(modelo_value === ''){
                $("#certificado_frente_preview").css("display", 'none');
                $("#certificado_frente_preview").attr("src", '');
                return false;
            }

            App.blockUI();
            $.ajax({
                url: '/modelo-do-certificado/carregar-ajax/'+ modelo_value,
                type: 'GET',
                beforeSend : function() {
                },
                complete: function () {
                },
                success: function (data) {

                    $("#certificado_frente_preview").css("display", 'block');
                    $("#certificado_frente_preview").attr("src", '/assets/certificados/frente/'+ data.bg_frente);

                    App.unblockUI();
                },
                error: function () {
                    App.blockUI();
                    alert('Ops algo deu errado');
                }
            });
        });

        $( "#tabela-criterios select" ).change(function(e) {
            validarCriteriosDoCertificado();
        });

        $('#tipo').change(function (e) {
            if($(this).val() ===  'frente'){
                $('#container-verso').hide()
            }else{
                $('#container-verso').show()
            }
        });

        $('.btn-transform-text').click(function (e) {
           var input = $(this).parent().parent().find('input');
           input.toggleClass('uppercase');
        });



        $( "form" ).submit(function(e) {
            var valid  = validarCriteriosDoCertificado();

            if($('#summernote_').summernote('isEmpty')){
                alert('Infome o texto da frente do certificado')
            }

            if($('#summernote_2').summernote('isEmpty') && $('#tipo').val() === 'frente_verso'){
                alert('Infomer o texto do verso do certificado')
            }


            if(!valid || $('#summernote_').summernote('isEmpty') || ($('#summernote_2').summernote('isEmpty') && $('#tipo').val() == 'frente_verso')){
                e.preventDefault();
            }
        });

        $('#summernote_').summernote({
            height: 250,   //set editable area's height
            codemirror: { // codemirror options
                theme: 'monokai'
            }
        });

        $('#summernote_2').summernote({
            height: 250,   //set editable area's height
            codemirror: { // codemirror options
                theme: 'monokai'
            }
        });
    });

    /**
     * Verifica se existem criterios repetidos
     */
    function validarCriteriosDoCertificado() {
        var tabela_criterios    = $( "#tabela-criterios");
        var tiposAtividade   = $("#tabela-criterios .tiposAtividade");
        var funcoes          = $("#tabela-criterios .funcoes");

        tabela_criterios.find('tr').css('background', '#fff');
        for(var i = 0; i < tiposAtividade.length; i++){

            for(var j = 0; j < tiposAtividade.length; j++){
                if(j !== i){
                    if(
                        tiposAtividade[i].value === tiposAtividade[j].value
                        && funcoes[i].value === funcoes[j].value
                    ){
                        tabela_criterios.find('tr:eq('+ (i+1)+')').css('background', '#FCD8C0');
                        tabela_criterios.find('tr:eq('+ (j+1)+')').css('background', '#FCD8C0');
                        alert('As linhas destacadas em "Críterios do modelo do certificado" se repetem, remova ou altere um dos critérios destacados');
                        return false;
                    }
                }
            }
        }

        return true;
    }

    <?php $this->headScript()->captureEnd() ?>
</script>