<div class="portlet light">
	<div class="portlet-title">
		<div class="caption">
			<i class="fa fa-bell font-green" aria-hidden="true"></i> <span
				class="caption-subject font-green bold uppercase"> Enviar aviso</span>
			<span class="caption-helper"></span>
		</div>
		<div class="actions">
			<a class="btn  btn-icon-only btn-default fullscreen"
				href="javascript:;" data-original-title="" title=""> </a>
		</div>
	</div>
	<div class="portlet-body" style="height: auto;">
        <?php echo $this->partial('partial/messages');?>
        <?php
        echo $this->partial('partial/form/general/quick', array(
            'form' => $this->form,
            'col_1' => 'col-md-2',
            'col_2' => 'col-md-9',
            'send' => true
        ));
        ?>
    </div>
</div>