<?php
/** @var  $row \Application\Entity\Cliente */
$data = $this->data;
?>


<div class="portlet light">
	<div class="portlet-title">
		<div class="caption">
			<i class="fa fa-users font-green" aria-hidden="true"></i> <span
				class="caption-subject font-green bold uppercase"> Clientes</span> <span
				class="caption-helper"></span>
		</div>
		<div class="actions">
			<a
				href="<?php echo $this->url('cliente/default', array('action' => 'cadastrar'))?>"
				class="btn green "> <i class="fa fa-plus" style="padding-right: 5px"></i>
				Novo
			</a> <a class="btn  btn-icon-only btn-default fullscreen"
				href="javascript:;" data-original-title="" title=""> </a>
		</div>
	</div>
	<div class="portlet-body" style="height: auto;">
        <?php echo $this->partial('partial/messages');?>

        <table class="table table-hover table-light" id="sample_1">
			<thead>
				<tr>
					<th>Código</th>
					<th>Nome</th>
					<th>Telefone 1</th>
					<th>Telefone 2</th>
					<th>Cadastrado em</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
            <?php foreach($data as $row): ?>
                <tr>
					<td><?php echo $row->getId(); ?></td>
					<td><?php echo $row->getNomeOuRazaoSocial(); ?></td>
					<td><?php echo $row->getTelefone1(); ?></td>
					<td><?php echo $row->getTelefone2(); ?></td>
					<td><?php echo $row->getCadastradoEm()->format('d/m/Y h:i:s'); ?></td>
					<td style="text-align: center;">
						<div class="clearfix">
							<a
								href="<?php  echo $this->url('cliente/default', array('action' => 'editar', 'id' => $row->getId()));?>"
								class="btn btn-icon-only yellow-saffron" title="Editar"> <i
								class="fa fa-pencil" aria-hidden="true"></i>
							</a> <a
								href="<?php  echo $this->url('cliente/default', array('action' => 'editar', 'id' => $row->getId()));?>"
								class="btn btn-icon-only blue-sharp" title="Mais informações"> <i
								class="fa fa-info" aria-hidden="true"></i>
							</a>
						</div>

					</td>
				</tr>
            <?php endforeach; ?>
        
		
		</table>
	</div>
</div>
