<?php
/** @var  $row \Application\Entity\Aviso */
$data = $this->data;
?>


<div class="portlet light">
	<div class="portlet-title">
		<div class="caption">
			<i class="fa fa-bell font-green" aria-hidden="true"></i> <span
				class="caption-subject font-green bold uppercase"> Aviso</span> <span
				class="caption-helper"></span>
		</div>
		<div class="actions">
			<a
				href="<?php echo $this->url('aviso/default', array('action' => 'cadastrar'))?>"
				class="btn green border-white sbold"> <i class="fa fa-plus"></i>
				NOVO AVISO
			</a> <a class="btn  btn-icon-only btn-default fullscreen"
				href="javascript:;" data-original-title="" title=""> </a>
		</div>
	</div>
	<div class="portlet-body" style="height: auto;">
        <?php echo $this->partial('partial/messages');?>

        <table class="table table-hover table-light" id="sample_1">
			<thead>
				<tr>
					<th>Nome</th>
					<th>Cadastrado em</th>
					<th>Última atualização</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
            <?php foreach($data as $row): ?>
                <tr>
					<td><?php echo $row->getCurso(); ?></td>
					<td><?php echo $row->getCadastradoEm()->format('d/m/Y h:i:s'); ?></td>
					<td><?php echo $row->getUltimaAtualizacao()->format('d/m/Y h:i:s'); ?></td>
					<td><a
						href="<?php  echo $this->url('aviso/default', array('action' => 'editar', 'id' => $row->getId()));?>"
						class="btn btn-icon-only yellow-saffron" title="Editar"> <i
							class="fa fa-pencil" aria-hidden="true"></i>
					</a></td>
				</tr>
            <?php endforeach; ?>
        
		
		</table>
	</div>
</div>
