<div class="page-sidebar-wrapper">
	<div class="page-sidebar navbar-collapse collapse"
		style="margin-top: 12px;">
		<ul class="page-sidebar-menu   " data-keep-expanded="false"
			data-auto-scroll="true" data-slide-speed="200">
			<li class="nav-item  "><a
				href="<?php echo $this->url('participante/default', array('action' => 'certificados'))?>"
				class="nav-link nav-toggle"> <i class="fa fa-certificate"
					aria-hidden="true"></i> <span class="title">Meus certificados </span>
			</a></li>
		</ul>
	</div>
</div>
