<div class="page-sidebar-wrapper">
	<!-- BEGIN SIDEBAR -->
	<!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
	<!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
	<div class="page-sidebar navbar-collapse collapse"
		style="margin-top: 12px;">
		<!-- BEGIN SIDEBAR MENU -->
		<!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
		<!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
		<!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
		<!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
		<!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
		<!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
		<ul class="page-sidebar-menu   " data-keep-expanded="false"
			data-auto-scroll="true" data-slide-speed="200">
			<li class="nav-item start "><a
				href="<?php echo $this->url('administrador/default', array('action' => 'dashboard'))?>"
				class="nav-link nav-toggle"> <i class="icon-home"></i> <span
					class="title">Dashboard</span>
			</a></li>

            <li class="nav-item start "><a
                        href="<?php echo $this->url('evento/default', array('action' => 'listar'))?>"
                        class="nav-link nav-toggle">
                    <i class="fa fa-calendar" aria-hidden="true"></i> <span class="title">Eventos</span>
                </a>
            </li>

			<li class="nav-item  "><a
				href="<?php echo $this->url('participante/default', array('action' => 'listar'))?>"
				class="nav-link nav-toggle"> <i class="fa fa-user"
					aria-hidden="true"></i> <span class="title">Participantes</span>
			</a></li>


			<li class="nav-item  "><a
				href="<?php echo $this->url('funcao/default', array('action' => 'listar'))?>"
				class="nav-link nav-toggle"> <i class="fa fa-book"
					aria-hidden="true"></i> <span class="title">Funções</span>
			</a></li>

            <li class="nav-item  "><a
                        href="<?php echo $this->url('tipo-atividade/default', array('action' => 'listar'))?>"
                        class="nav-link nav-toggle"> <i class="fa fa-cog"
                                                        aria-hidden="true"></i> <span class="title">Tipo de atividades</span>
                </a></li>



			<li class="nav-item  "><a
				href="<?php echo $this->url('usuario/default', array('action' => 'listar'))?>"
				class="nav-link nav-toggle"> <i class="fa fa-users"
					aria-hidden="true"></i> <span class="title">Usuários</span>
			</a></li>


			<li class="heading">
				<h3 class="uppercase">CONTROLE DE ACESSO</h3>
			</li>

			<li class="nav-item  "><a
				href="<?php echo $this->url('acl-privileges/default', array('action' => 'listar'))?>"
				class="nav-link nav-toggle"> <i class="fa fa-key"></i> <span
					class="title">Privilégios</span>
			</a></li>

			<li class="nav-item  "><a
				href="<?php echo $this->url('acl-resources/default', array('action' => 'listar'))?>"
				class="nav-link nav-toggle"> <i class="fa fa-lock"></i> <span
					class="title">Recursos</span>
			</a></li>

			<li class="nav-item  "><a
				href="<?php echo $this->url('acl-roles/default', array('action' => 'listar'))?>"
				class="nav-link nav-toggle"> <i class="fa fa-user"></i> <span
					class="title">Papéis</span>
			</a></li>

		</ul>
		<!-- END SIDEBAR MENU -->
	</div>
	<!-- END SIDEBAR -->
</div>
