<?php
/** @var  $row \Application\Entity\Atividade */
/** @var  $evento \Application\Entity\Evento */
$data = $this->data;
$evento = $this->evento;
?>

<div class="portlet light">
	<div class="portlet-title">
		<div class="caption">

			<i class="fa fa-graduation-cap font-green" aria-hidden="true"></i> <span
				class="caption-subject font-green bold uppercase"> Cadastrar
				atividade</span> <span class="caption-helper"></span>
		</div>
        <div class="actions">
            <?php echo $this->partial('evento/menu/superior', array(
                'evento' => $evento
            ));?>
            <a class="btn  btn-icon-only btn-default fullscreen"
               href="javascript:;" data-original-title="" title=""> </a>
        </div>
	</div>
	<div class="portlet-body" style="height: auto;">

        <?php echo $this->partial('evento/table/detalhes', array(
            'evento' => $evento
        ));?>


        <?php echo $this->partial('partial/messages');?>
        <?php
        echo $this->partial('partial/form/general/quick', array(
            'form' => $form
        ));
        ?>
    </div>
</div>
