<?php
/** @var  $evento \Application\Entity\Evento */
$evento = $this->evento;
?>
<div class="table-scrollable" style="    margin: 10px 0 40px 0 !important;">
    <table class="table table-bordered table-hover" style="background: #f5f5f5;">
        <tr>
            <td class="sbold">Evento</td>
            <td  colspan="5"><?php echo $evento->getNome(); ?> (<?php echo $evento->getSigla(); ?>)</td>
        </tr>

        <tr>
            <td class="sbold">Período</td>
            <td><?php echo $evento->getDataFormatada($evento->getDataInicial(), $evento->getDataFinal()); ?></td>
            <td class="sbold">Ano</td>
            <td><?php echo $evento->getAno(); ?></td>
            <td class="sbold">Edição</td>
            <td><?php echo $evento->getNumeroEdicao(); ?></td>
        </tr>
    </table>
</div>