<style>
    table span{
        background: transparent;
    }
    table input[type=text]{
        width: 230px;
    }
</style>

<table style="width: 100%; margin: 10px 0 40px 0;" class="table table-bordered table-hover">
    <thead>
    <tr>
        <th>Tag</th>
        <th></th>
        <th></th>
        <th>Descrição</th>
        <th>Exemplo do valor retornado</th>
    </tr>
    </thead>
    <tbody>

    <tr class="mt-clipboard-container">
        <td>
            <input type="text" value="[atividade_carga_horaria]" readonly id="mt-target-9" class="form-control">
        </td>
        <td colspan="2">
            <a href="javascript:;" title="Clique aqui para copiar a tag" class="btn blue-steel mt-clipboard" data-clipboard-action="copy" data-clipboard-target="#mt-target-9">
                <i class="fa fa-copy" title="Clique aqui para copiar a tag"></i>
            </a>
        </td>
        <td>Retorna a carga horária da atividade</td>
        <td>Ex: 4 horas</td>
    </tr>


    <tr class="mt-clipboard-container">
        <td>
            <input type="text" value="[atividade_periodo]" readonly id="mt-target-10" class="form-control">
        </td>

        <td>
            <a href="javascript:;" class="btn blue-steel mt-clipboard" data-clipboard-action="copy" data-clipboard-target="#mt-target-10">
                <i class="fa fa-copy" title="Clique aqui para copiar a tag"></i>
            </a>
        </td>
        <td>
            <a href="javascript:;" title="Maiúsculas e minúsculas" class="btn green-dark mt-clipboard btn-transform-text">
                <i class="fa fa-font" title="Maiúsculas e minúsculas"></i>
            </a>
        </td>
        <td>Retorna um texto com o período da atividade.</td>
        <td>Ex: 20 de agosto a 22 de agosto de 2017</td>
    </tr>

    <tr class="mt-clipboard-container">
        <td>
            <input type="text" value="[atividade_titulo]" readonly id="mt-target-8" class="form-control">
        </td>

        <td>
            <a href="javascript:;" title="Clique aqui para copiar a tag" class="btn blue-steel mt-clipboard" data-clipboard-action="copy" data-clipboard-target="#mt-target-8">
                <i class="fa fa-copy" title="Clique aqui para copiar a tag"></i>
            </a>
        </td>
        <td>
            <a href="javascript:;" title="Maiúsculas e minúsculas" class="btn green-dark mt-clipboard btn-transform-text">
                <i class="fa fa-font" title="Maiúsculas e minúsculas"></i>
            </a>
        </td>
        <td>Retorna o nome da atividade</td>
        <td>Ex: Netlogo: ambiente de simulação multiagente</td>
    </tr>

    <tr class="mt-clipboard-container">
        <td colspan="4" style="padding: 10px;"></td>
    </tr>

    <tr class="mt-clipboard-container">
        <td>
            <input type="text" value="[evento_ano]" readonly id="mt-target-6" class="form-control">
        </td>
        <td colspan="2">
            <a href="javascript:;" title="Clique aqui para copiar a tag" class="btn blue-steel mt-clipboard" data-clipboard-action="copy" data-clipboard-target="#mt-target-6">
                <i class="fa fa-copy" title="Clique aqui para copiar a tag"></i>
            </a>
        </td>
        <td>Retorna o ano do evento no formato YYYY</td>
        <td>Ex: 2017</td>
    </tr>


    <tr class="mt-clipboard-container">
        <td>
            <input type="text" value="[evento_nome]" readonly id="mt-target-4" class="form-control">
        </td>

        <td>
            <a href="javascript:;" title="Clique aqui para copiar a tag" class="btn blue-steel mt-clipboard" data-clipboard-action="copy" data-clipboard-target="#mt-target-4">
                <i class="fa fa-copy" title="Clique aqui para copiar a tag"></i>
            </a>
        </td>
        <td>
            <a href="javascript:;" title="Maiúsculas e minúsculas" class="btn green-dark mt-clipboard btn-transform-text">
                <i class="fa fa-font" title="Maiúsculas e minúsculas"></i>
            </a>
        </td>
        <td>Retorna o nome evento</td>
        <td>Ex: Semana de Tecnologia da Informação Week-IT</td>
    </tr>


    <tr class="mt-clipboard-container">
        <td>
            <input type="text" value="[evento_periodo]" readonly id="mt-target-7" class="form-control">
        </td>
        <td colspan="2">
            <a href="javascript:;" title="Clique aqui para copiar a tag" class="btn blue-steel mt-clipboard" data-clipboard-action="copy" data-clipboard-target="#mt-target-7">
                <i class="fa fa-copy" title="Clique aqui para copiar a tag"></i>
            </a>
        </td>
        <td>Retorna um texto com o período do evento.</td>
        <td>Ex: 25 de julho a 19 de dezembro de 2014</td>
    </tr>


    <tr class="mt-clipboard-container">
        <td>
            <input type="text" value="[evento_sigla]" readonly id="mt-target-5" class="form-control">
        </td>

        <td>
            <a href="javascript:;" title="Clique aqui para copiar a tag" class="btn blue-steel mt-clipboard" data-clipboard-action="copy" data-clipboard-target="#mt-target-5">
                <i class="fa fa-copy" title="Clique aqui para copiar a tag"></i>
            </a>
        </td>
        <td>
            <a href="javascript:;" title="Maiúsculas e minúsculas" class="btn green-dark mt-clipboard btn-transform-text">
                <i class="fa fa-font" title="Maiúsculas e minúsculas"></i>
            </a>
        </td>
        <td>Retorna a sigla evento</td>
        <td>Ex: WeekIT</td>
    </tr>

    <tr class="mt-clipboard-container">
        <td colspan="4" style="padding: 10px;"></td>
    </tr>

    <tr class="mt-clipboard-container">
        <td>
            <input type="text" value="[funcao_nome]" readonly id="mt-target-11" class="form-control">
        </td>

        <td>
            <a href="javascript:;" title="Clique aqui para copiar a tag" class="btn blue-steel mt-clipboard" data-clipboard-action="copy" data-clipboard-target="#mt-target-11">
                <i class="fa fa-copy" title="Clique aqui para copiar a tag"></i>
            </a>
        </td>
        <td>
            <a href="javascript:;" title="Maiúsculas e minúsculas" class="btn green-dark mt-clipboard btn-transform-text">
                <i class="fa fa-font" title="Maiúsculas e minúsculas"></i>
            </a>
        </td>
        <td>Retorna o nome da função.</td>
        <td>Ex: bolsista</td>
    </tr>

    <tr class="mt-clipboard-container">
        <td colspan="4" style="padding: 10px;"></td>
    </tr>



    <tr class="mt-clipboard-container">
        <td>
            <input type="text" value="[participacao_carga_horaria]" readonly id="mt-target-3" class="form-control">
        </td>
        <td colspan="2">
            <a href="javascript:;" title="Clique aqui para copiar a tag" class="btn blue-steel mt-clipboard" data-clipboard-action="copy" data-clipboard-target="#mt-target-3">
                <i class="fa fa-copy" title="Clique aqui para copiar a tag"></i>
            </a>
        </td>
        <td title="Retorna a carga horária da participação">Retorna a carga horária da participação.</td>
        <td>Ex: 4 horas</td>
    </tr>

    <tr class="mt-clipboard-container">
        <td>
            <input type="text" value="[participacao_periodo]" readonly id="mt-target-21" class="form-control">
        </td>
        <td colspan="2">
            <a href="javascript:;" class="btn blue-steel mt-clipboard" data-clipboard-action="copy" data-clipboard-target="#mt-target-21">
                <i class="fa fa-copy" title="Clique aqui para copiar a tag"></i>
            </a>
        </td>
        <td>Retorna um texto com o período da participação.</td>
        <td>Ex: 25 de julho a 19 de dezembro de 2018</td>
    </tr>

    <tr class="mt-clipboard-container">
        <td>
            <input type="text" value="[participacao_qtd_bolsita]" readonly id="mt-target-12" class="form-control">
        </td>
        <td colspan="2">
            <a href="javascript:;" class="btn blue-steel mt-clipboard" data-clipboard-action="copy" data-clipboard-target="#mt-target-12">
                <i class="fa fa-copy" title="Clique aqui para copiar a tag"></i>
            </a>
        </td>
        <td>Retorna a quantidade de bolsistas por extenso.</td>
        <td>Ex: quatro</td>
    </tr>




    <tr class="mt-clipboard-container">
        <td colspan="4" style="padding: 10px;"></td>
    </tr>

    <tr class="mt-clipboard-container">
        <td>
            <input type="text" value="[participante_cpf]" readonly id="mt-target-2" class="form-control">
        </td>
        <td colspan="2">
            <a href="javascript:;" title="Clique aqui para copiar a tag" class="btn blue-steel mt-clipboard" data-clipboard-action="copy" data-clipboard-target="#mt-target-2">
                <i class="fa fa-copy" title="Clique aqui para copiar a tag"></i>
            </a>
        </td>
        <td>Retorna o CPF do participante</td>
        <td>Ex: 056.579.968-00</td>
    </tr>

    <tr class="mt-clipboard-container">
        <td>
            <input type="text" value="[participante_data_nascimento]" readonly id="mt-target-13" class="form-control">
        </td>
        <td colspan="2">
            <a href="javascript:;" title="Clique aqui para copiar a tag" class="btn blue-steel mt-clipboard" data-clipboard-action="copy" data-clipboard-target="#mt-target-13">
                <i class="fa fa-copy" ></i>
            </a>
        </td>
        <td>Retona a data de nascimento do participante no formato
            dia/mês/ano</td>
        <td>Ex: 12/08/1993</td>
    </tr>

    <tr class="mt-clipboard-container">
        <td>
            <input type="text" value="[participante_nome]" readonly id="mt-target-1" class="form-control">
        </td>

        <td>
            <a href="javascript:;" title="Clique aqui para copiar a tag" class="btn blue-steel mt-clipboard"  data-clipboard-target="#mt-target-1">
                <i class="fa fa-copy" title="Clique aqui para copiar a tag"></i>
            </a>
        </td>
        <td>
            <a href="javascript:;" title="Maiúsculas e minúsculas" class="btn green-dark mt-clipboard btn-transform-text">
                <i class="fa fa-font" title="Maiúsculas e minúsculas"></i>
            </a>
        </td>
        <td>Retorna o nome do participante</td>
        <td>Ex: João da Silva</td>
    </tr>


    <tr class="mt-clipboard-container">
        <td colspan="4" style="padding: 10px;"></td>
    </tr>


</table>



<?php $this->headScript()->captureStart() ?>
<script type="text/javascript">
    $(document).ready(function() {
        $('#summernote').summernote({
            codemirror: { // codemirror options
                theme: 'monokai'
            }
        });
    });
</script>
<?php $this->headScript()->captureEnd() ?>
