<div class="portlet light">
	<div class="portlet-title">
		<div class="caption">

			<i class="fa fa-user font-green" aria-hidden="true"></i> <span
				class="caption-subject font-green bold uppercase"> Cadastrar
				participante por planilha</span> <span class="caption-helper"></span>
		</div>
		<div class="actions">
			<a class="btn  btn-icon-only btn-default fullscreen"
				href="javascript:;" data-original-title="" title=""> </a>
		</div>
	</div>

	<div class="portlet-body">

		<div class="note note-info">
			<h4 class="block">Atenção</h4>
			<p>
				Para que o cadastro seja executado com sucesso a planilha enviada
				deve ter os campos <b>CPF</b>, <b>Nome completo</b> e <b>Data de
					nascimento</b>. Na ausência de um desses campos o cadastro do
				participante não será executado. Os campos <b>Email</b> e <b>Instituição</b>
				são opcionais. Quarquer outra coluna da planilha será ignorada
			</p>
		</div>

		<div style="padding: 0 0 30px 0;">
			<a
				href="<?php echo $this->url('publico/default', array('action' => 'download-cadastrar-participante-por-planilha'));?>"
				class="btn btn blue" id="blockui_sample_1_3"> <i
				class="fa fa-download"></i> Baixar planilha de exemplo
			</a>
		</div>


        <?php echo $this->partial('partial/messages');?>

        <?php
        if ($this->formElementErrors($form->get('planilha')))
            echo $this->formElementErrors()
                ->setMessageOpenFormat('<div class="note note-danger" style="margin-bottom: 10px">')
                ->setMessageSeparatorString('</div><div %s style="margin-bottom: 10px">')
                ->setMessageCloseString('</div>')
                ->render($form->get('planilha'));
        ?>

        <div class="portlet light bordered "
			style="background: #f5f5f5;">
			<div class="portlet-body">
                <?php $form = $this->form; ?>
                <?php $form->prepare(); ?>
                <?php echo $this->form()->openTag($form); ?>

                <div class="form-group">
					<label class="sr-only" for="exampleInputEmail2">Email address</label>
                    <?php echo $this->formElement($form->get('planilha')); ?>
                </div>

			</div>

		</div>
	</div>

	<div class="form-actions">
		<div class="row">
			<div class="col-md-12">
				<button type="submit" class="btn btn green-jungle pull-right"
					id="blockui_sample_1_3">
					<i class="fa fa-send-o "></i> Enviar planilha
				</button>
			</div>
		</div>
	</div>
    <?php echo $this->form()->closeTag($form); ?>
</div>
</div>
