<div class="portlet light">
	<div class="portlet-title">
		<div class="caption">

			<i class="fa fa-certificate font-green" aria-hidden="true"></i> <span
				class="caption-subject font-green bold uppercase"> Meus Certificados</span>
			<span class="caption-helper"></span>
		</div>
		<div class="actions">
			<a class="btn  btn-icon-only btn-default fullscreen"
				href="javascript:;" data-original-title="" title=""> </a>
		</div>
	</div>
	<div class="portlet-body" style="height: auto;">
        <?php echo $this->partial('partial/messages');?>
    </div>
</div>
