<?php
/** @var  $element Zend\Form\Element\Text*/
$element = $this->element;

$col_1 = ($this->col_1) ? $this->col_1 : 'col-md-2';
$col_2 = ($this->col_2) ? $this->col_2 : 'col-md-6';

?>

<div class="form-group <?php if($this->formElementErrors($element)) echo " has-error";   ?>">
	<label
		class="<?php echo $col_1;?> control-label <?php  echo (isset($element->getLabelAttributes()['class'])) ? $element->getLabelAttributes()['class'] : '';?> ">
        <?php echo $element->getLabel();?>
    </label>
	<div class="<?php echo $col_2;?>">
<?php $element->setAttribute('class', 'form-control ' .  $element->getAttribute('class')) ?>
<?php echo $this->formElement($element); ?>

<?php if(!empty($element->getAttribute('description'))): ?>
    <span class="help-inline"> <?php echo $element->getAttribute('description'); ?> </span>
<?php endif; ?>

<?php

echo $this->partial('partial/form/general/quick/message-erros', array(
    'element' => $element
))?>
</div>
</div>
