<?php

/** @var $this \Zend\View\Renderer\PhpRenderer */
/** @var  $usuario \Application\Entity\Usuario*/
$container = new \Zend\Session\Container('logado');
$usuario = $container->offsetGet('usuario');
/** @var  $row \Application\Entity\Usuario */
$data = $this->data;
?>


<div class="portlet light">
	<div class="portlet-title">
		<div class="caption">
			<i class="fa fa-users font-green" aria-hidden="true"></i> <span
				class="caption-subject font-green bold uppercase"> Usuários</span> <span
				class="caption-helper"></span>
		</div>
		<div class="actions">
			<a
				href="<?php echo $this->url('usuario/default', array('action' => 'cadastrar'))?>"
				class="btn green border-white sbold"> <i class="fa fa-plus"></i>
				CADASTRAR USUÁRIO
			</a> <a class="btn  btn-icon-only btn-default fullscreen"
				href="javascript:;" data-original-title="" title=""> </a>
		</div>
	</div>
	<div class="portlet-body" style="height: auto;">
        <?php echo $this->partial('partial/messages');?>

        <table class="table table-hover table-light" id="sample_1">
			<thead>
				<tr>
					<th>Login</th>
					<th>Email</th>
					<th>Tipo</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
            <?php foreach($data as $row): ?>
                <tr>
					<td><?php echo $row->getLogin(); ?></td>
					<td><?php echo $row->getEmail(); ?></td>
					<td><?php echo $row->getTipo(); ?></td>

					<td style="text-align: right; width: 167px;">
						<div class="clearfix">

                            <a
								href="<?php  echo $this->url('usuario/default', array('action' => 'editar', 'id' => $row->getId()));?>"
								class="btn btn-icon-only yellow-saffron" title="Editar"> <i
								class="fa fa-pencil" aria-hidden="true"></i>
							</a> <a
								href="<?php  echo $this->url('usuario/default', array('action' => 'deletar', 'id' => $row->getId()));?>"
								class="btn btn-icon-only red" title="Deletar usuário"
								onclick="return confirm('Confirmar exclusão de usuário ?');"> <i
								class="fa fa-trash" aria-hidden="true"></i>
							</a>
						</div>
					</td>
				</tr>
            <?php endforeach; ?>
        
		
		</table>
	</div>
</div>
