<?php

$data = $this->data;
$container = (new \Zend\Session\Container('logado'));
$evento_selecionado = $container->offsetGet('evento_selecionado');

?>

<?php if($container->offsetExists('evento_selecionado')):?>

    <div class="portlet light">
        <div class="portlet-title">
            <div class="page-head" style="margin-bottom: 10px;">
                <!-- BEGIN PAGE TITLE -->
                <div class="page-title">
                    <h1><?php echo $evento_selecionado['nome'];?> (<?php echo $evento_selecionado['sigla'];?>)
                        <small>Edição: <?php echo $evento_selecionado['numero_edicao']; ?> - Ano: <?php echo $evento_selecionado['ano']; ?></small>
                    </h1>
                </div>
                <!-- END PAGE TITLE -->
                <!-- BEGIN PAGE TOOLBAR -->
                <div class="page-toolbar">

                    <!-- BEGIN THEME PANEL -->
                    <div class="btn-group btn-theme-panel  green">
                        <a href="javascript:;" class="btn dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-calendar"></i>&nbsp;
                            <span class="thin uppercase hidden-xs"></span>&nbsp;
                            <i class="fa fa-angle-down"></i>
                        </a>
                        <div class="dropdown-menu theme-panel pull-right dropdown-custom hold-on-click">
                            <h4 class="col-md-12 control-label">Alterar evento</h4>
                            <div class="col-md-12">
                                <select class="form-control" id="opcoes-eventos">
                                    <?php /** @var $row  \Application\Entity\Evento*/ ?>
                                    <?php foreach($data['eventos'] as $row): ?>
                                        <option value="<?php echo $row->getId()?>" <?php echo ($row->getId() == $evento_selecionado['id']) ? 'selected' : ''?>><?php echo $row; ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <!-- END THEME PANEL -->
                </div>
                <!-- END PAGE TOOLBAR -->
            </div>
        </div>
        <div class="portlet-body" style="height: auto;">

            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <div class="dashboard-stat blue">
                        <div class="visual">
                            <i class="fa fa-user"></i>
                        </div>
                        <div class="details">
                            <div class="number">
                            <span data-counter="counterup"
                                  data-value="<?php echo $data['total_participantes']; ?>">
                                <?php echo $data['total_participantes']; ?>
                            </span>
                            </div>
                            <div class="desc">Participantes</div>
                        </div>
                        <a class="more"
                           href="<?php  echo $this->url('participante/default', array('action' => 'listar'));?>">
                            Ver todos os participantes <i class="m-icon-swapright m-icon-white"></i>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <div class="dashboard-stat red">
                        <div class="visual">
                            <i class="fa fa-users"></i>
                        </div>
                        <div class="details">
                            <div class="number">
                        <span data-counter="counterup" data-value="<?php echo $data['total_de_participacoes']; ?>">
                        <?php echo $data['total_de_participacoes']; ?>
                            </div>
                            <div class="desc">Participações</div>
                        </div>
                        <a class="more"
                           href="<?php  echo $this->url('participacao/default', array('action' => 'cadastrar', 'evento' => $evento_selecionado['id']));?>">
                            Ver mais <i class="m-icon-swapright m-icon-white"></i>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <div class="dashboard-stat green-jungle">
                        <div class="visual">
                            <i class="fa fa fa-book"></i>
                        </div>
                        <div class="details">
                            <div class="number">
					<span data-counter="counterup"
                          data-value="<?php echo $data['total_de_atividades']; ?>"><?php echo $data['total_de_atividades']; ?></span>
                            </div>
                            <div class="desc">Atividades</div>
                        </div>
                        <a class="more" href="<?php  echo $this->url('atividade/default', array('action' => 'listar', 'evento' => $evento_selecionado['id']));?>">
                            Ver mais <i class="m-icon-swapright m-icon-white"></i>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <div class="dashboard-stat yellow-lemon">
                        <div class="visual">
                            <i class="fa fa-globe"></i>
                        </div>
                        <div class="details">
                            <div class="number">
                                <span data-counter="counterup" data-value="<?php echo $data['total_de_certificados_emitidos']; ?>">
                                <?php echo $data['total_de_certificados_emitidos']; ?>
                            </div>
                            <div class="desc">Certificados emitidos</div>
                        </div>
                        <a class="more"
                           href="<?php  echo $this->url('participacao/default', array('action' => 'enviar-certificados-por-email', 'evento' => $evento_selecionado['id']));?>">
                            Ver mais <i class="m-icon-swapright m-icon-white"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="portlet light">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-calendar font-green" aria-hidden="true"></i> <span
                        class="caption-subject font-green bold uppercase"> Participações</span>
                <span class="caption-helper"></span>
            </div>
            <div class="actions">
                <a class="btn  btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
            </div>
        </div>
        <div class="portlet-body" style="height: auto;">
            <table class="table table-hover table-light" id="sample_1">
                <thead>
                <tr>
                    <th>CPF</th>
                    <th>Nome</th>
                    <th>Atividade</th>
                    <th>Tipo</th>
                    <th>Início</th>
                    <th>Fim</th>
                </tr>
                </thead>
                <tbody>
                <?php
                /** @var  $row \Application\Entity\Participacao */
                foreach($data['participacoes'] as $row): ?>
                    <tr>
                        <td><?php echo $row->getParticipante()->getCpf(); ?></td>
                        <td><?php echo $row->getParticipante()->getNomeCompleto(); ?></td>
                        <td><?php echo $row->getAtividade(); ?></td>
                        <td><?php echo $row->getAtividade()->getTipoAtividade()->getNome(); ?></td>
                        <td><?php echo $row->getDataInicio()->format('d/m/Y'); ?></td>
                        <td><?php echo $row->getDataFim()->format('d/m/Y'); ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
<?php endif; ?>



<script type="text/javascript">
<?php $this->headScript()->captureStart() ?>

$('#opcoes-eventos').change(function () {
    App.blockUI();
    window.location = "/coordenador/dashboard/"+ $('#opcoes-eventos').val();
});

<?php $this->headScript()->captureEnd() ?>
</script>



