<?php
$this->layout()->setVariable('titulo', 'Perfil');

/** @var  $usuario Application\Entity\Usuario*/
$container = new \Zend\Session\Container('logado');
$usuario = $container->offsetGet('usuario');
?>

<div class="row">
	<div class="col-md-3">

		<!-- Profile Image -->
		<div class="box box-primary">
			<div class="box-body box-profile">
				<img class="profile-user-img img-responsive img-circle"
					src="<?php echo $usuario['perfil']; ?>" alt="User profile picture">
				<h3 class="profile-username text-center"> <?php echo $usuario['nome']; ?></h3>
				<p class="text-muted text-center"><?php echo ucfirst( $usuario['tipo']); ?></p>

				<ul class="list-group list-group-unbordered">
					<li class="list-group-item"><b>Cadastrado em</b> <a
						class="pull-right"><?php echo $usuario['cadastrado_em']->format('d/m/Y H:i');?></a>
					</li>
					<li class="list-group-item"><b>Atualização</b> <a
						class="pull-right"><?php echo $usuario['ultima_atualizacao']->format('d/m/Y H:i');?></a>
					</li>
				</ul>

				<a
					href="<?php echo $this->url('contador/default', array('action' => 'log'))?>"
					class="btn btn-primary btn-block"><b>Verificar log</b></a>
			</div>
			<!-- /.box-body -->
		</div>
		<!-- /.box -->

	</div>
	<!-- /.col -->
	<div class="col-md-9">
		<div class="box box-primary">
			<div class="box-body">
				<!-- form start -->
                <?php $form->prepare(); ?>
                <?php echo $this->form()->openTag($form); ?>
                <?php echo $this->partial('partial/messages');?>

                <div class="box-header with-border"
					style="margin-bottom: 10px;">
					<h3 class="box-title">
						<i class="fa fa-user" style="padding-right: 5px"></i> Dados do
						cliente
					</h3>
				</div>
                <?php
                echo $this->partial('partial/form/general/quick/element/' . $form->get('id')
                    ->getAttribute('type'), array(
                    'element' => $form->get('id')
                ));
                ?>

                <?php
                echo $this->partial('partial/form/general/quick/element/' . $form->get('nome')
                    ->getAttribute('type'), array(
                    'element' => $form->get('nome')
                ));
                ?>

                <?php
                echo $this->partial('partial/form/general/quick/element/' . $form->get('sobrenome')
                    ->getAttribute('type'), array(
                    'element' => $form->get('sobrenome')
                ));
                ?>


                <?php
                echo $this->partial('partial/form/general/quick/element/' . $form->get('email')
                    ->getAttribute('type'), array(
                    'element' => $form->get('email')
                ));
                ?>

                <?php
                /**
                 * echo $this->partial('partial/form/general/quick/element/'.$form->get('image-file')->getAttribute('type'), array(
                 * 'element' => $form->get('image-file'),
                 * ));
                 * *
                 */
                ?>
                <div class="box-header with-border"
					style="margin-bottom: 10px;">
					<h3 class="box-title">
						<i class="fa fa-lock" style="padding-right: 5px; margin-top: 20px"></i>
						Senha
					</h3>
				</div>



                <?php
                echo $this->partial('partial/form/general/quick/element/' . $form->get('senha')
                    ->getAttribute('type'), array(
                    'element' => $form->get('senha')
                ));
                ?>

                <?php
                echo $this->partial('partial/form/general/quick/element/' . $form->get('confirmarsenha')
                    ->getAttribute('type'), array(
                    'element' => $form->get('confirmarsenha')
                ));
                ?>

                <?php
                echo $this->partial('partial/form/general/quick/element/' . $form->get('submit')
                    ->getAttribute('type'), array(
                    'element' => $form->get('submit')
                ));
                ?>
            </div>
			</form>
		</div>
	</div>
</div>
<!-- /.col -->
</div>
<!-- /.row -->