<?php
    /** @var  $modelo \Application\Entity\ModeloCertificado */
    /** @var  $participacao \Application\Entity\Participacao */
    $modelo = $this->modelo;
    $participacao = $this->participacao;
?>
<!DOCTYPE html>
<html lang="pt">

<head>
<meta charset="utf-8">
<title>Certificado - <?php echo $participacao->getChaveValidacao(); ?> - Certificados Online: Emissão e Validação / IFBA Vitória da Conquista</title>

<!-- Normalize or reset CSS with your favorite library -->
<link rel="stylesheet"
	href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">

<!-- Load paper.css for happy printing -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/paper-css/0.3.0/paper.css">

<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700" rel="stylesheet">

<!-- Set page size here: A5, A4 or A3 -->
<!-- Set also "landscape" if you need -->
<style type="text/css">
@page {
	size: A4 landscape;
	margin: 0;
}

body {
	font-family: 'Open Sans', sans-serif;
	padding-top: 20px;
	padding-bottom: 20px;
}

.sheet {
	margin: auto;
}

#img-background {
	position: absolute;
    width: 100%;
    height: 100%;
}

#texto {
    font-size: 1.7em;
    display: block;
    position: absolute;
    z-index: 2;
    top: 80mm;
    padding: 0 15mm 0;
    margin: 0;
    text-align: justify;
}

#texto p{
    text-align: justify !important;
}

#sheet-verso #texto{
    font-size: 1.2em;
    display: block;
    position: absolute;
    z-index: 2;
    top: 6mm;
    padding: 0;
    margin: 0;
    text-align: justify;
    width: 100% !important;
}

#sheet-verso #texto table {
    width: 60% !important;
    display: block;
    margin: 5px 50px;
}

#registro {
    font-size: 0.9em;
    display: block;
    position: absolute;
    z-index: 2;
    top: 196mm;
    margin: 0;
    text-align: right;
    right: 10mm;
    font-weight: 600;
}

#link-validar {
    font-size: 0.8em;
    display: block;
    position: absolute;
    z-index: 2;
    top: 201mm;
    margin: 0;
    text-align: right;
    right: 10mm;
    font-weight: 600;
}

#sheet-verso{
    margin-top: 20px;
}

#link-validar a {
    text-decoration: none;
}

@media print {
	body {
		padding-top: 0;
		padding-bottom: 0
	}
	.sheet {

	}

    #sheet-verso{
        margin-top: 0;
    }
}
</style>
</head>

<!-- Set "A5", "A4" or "A3" for class name -->
<!-- Set also "landscape" if you need -->
<body class="A4 landscape">

	<!-- Each sheet element should have the class "sheet" -->
	<!-- "padding-**mm" is optional: you can set 10, 15, 20 or 25 -->
	<section class="sheet">
		<img src="<?php echo $this->serverUrl('/assets/certificados/frente/'. $modelo['bg_frente']);?>" id="img-background" />
		<!-- Write HTML just like a web page -->
        <div id="texto">
            <?php echo $modelo['texto_frente'];?>
        </div>

        <div id="registro">
            Código de registro: <b><?php echo $this->certificadoFormat($participacao->getChaveValidacao()); ?></b>
        </div>

        <div id="link-validar">
            Verificar em: <a href="http://certificados.ifba.edu.br/validar" target="_blank">http://certificados.ifba.edu.br/validar</a>
        </div>
	</section>

  <?php if($modelo['tipo'] == 'frente_verso'): ?>
    <!-- Each sheet element should have the class "sheet" -->
    <!-- "padding-**mm" is optional: you can set 10, 15, 20 or 25 -->
    <section class="sheet" id="sheet-verso">
        <img src="<?php echo $this->serverUrl('/assets/certificados/verso/'. $modelo['bg_verso']);?>" id="img-background" />
        <!-- Write HTML just like a web page -->
        <div id="texto">
            <?php echo $modelo['texto_verso'];?>
        </div>
    </section>
    <?php endif; ?>
</body>
</html>