<?php
use Application\Entity\Participacao;
?>
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="pt-BR">
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
<meta charset="utf-8" />
<title>Validar - Certificados Online: Emissão e Validação / IFBA Vitória da Conquista</title>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="width=device-width, initial-scale=1" name="viewport" />
<meta content="" name="description" />
<meta content="Joabe Pinheiro" name="author" />
<!-- BEGIN GLOBAL MANDATORY STYLES -->
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
<link href="/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
<link href="/assets/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" />
<link href="/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="/assets/global/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css" />
<link href="/assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css" />
<!-- END GLOBAL MANDATORY STYLES -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<link href="/assets/global/plugins/select2/css/select2.min.css" rel="stylesheet" type="text/css" />
<link href="/assets/global/plugins/select2/css/select2-bootstrap.min.css" rel="stylesheet" type="text/css" />
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN THEME GLOBAL STYLES -->
<link href="/assets/global/css/components.min.css" rel="stylesheet" id="style_components" type="text/css" />
<link href="/assets/global/css/plugins.min.css" rel="stylesheet" type="text/css" />
<!-- END THEME GLOBAL STYLES -->
<!-- BEGIN PAGE LEVEL STYLES -->
<link href="/assets/pages/css/login-2.css" rel="stylesheet" type="text/css" />

<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN THEME LAYOUT STYLES -->
<!-- END THEME LAYOUT STYLES -->
<link rel="shortcut icon" href="img/favicon.ico" />
</head>
<!-- END HEAD -->

<body class=" login" style="background: #fff !important;">

<?php if(!empty($this->partipante)):?>

    <div id="cabecalho-emitir-validar">
        <a href="/validar">
            <img src="/assets/layouts/layout4/img/logo.png" alt="" class="center-block img-responsive" />

            <a class="btn red" id="botao-sair" href="/validar" data-original-title="" title="Sair">Sair</a>
        </a>
    </div>

	<div class="portlet light" id="container-participante" style="width: 80%;">
		<div class="portlet-title">
			<div class="caption">
				<i class="fa fa-user font-green" aria-hidden="true"></i>
                <span class="caption-subject font-green bold uppercase"> Dados do participante</span>
                <span class="caption-helper"></span>
			</div>
		</div>
		<div class="portlet-body" style="height: auto;">

			<table class="table table-light">
				<tbody>
					<tr>
						<td class="sbold">Nome:</td>
						<td><?php echo $this->partipante->getNomeCompleto(); ?></td>
					</tr>
					<tr>
						<td class="sbold">CPF:</td>
						<td><?php echo $this->CPF($this->partipante->getCpf()); ?></td>
					</tr>

				</tbody>
			</table>
		</div>
	</div>

<?php
    /**
     *
     * @var Participacao $participacao
     */
    $participacao = $this->participacao;
    ?>
<div class="portlet light" style="margin: auto; width: 80%;">
		<div class="portlet-title">
			<div class="caption">
				<i class="fa fa-certificate font-green" aria-hidden="true"></i> 
				<span class="caption-subject font-green bold uppercase"> Dados do certificado</span> 
				<span class="caption-helper"></span>
			</div>
		</div>
		<div class="portlet-body" style="height: auto;">

			<table class="table table-light">
				<tbody>
					<tr>
						<td class="sbold">Nome do evento:</td>
						<td>
                            <?php echo $participacao->getAtividade()->getEvento()->getNome(); ?>
                            <?php echo (!empty($participacao->getAtividade()->getEvento()->getSigla())) ? ' ('.$participacao->getAtividade()->getEvento()->getSigla().')' : ''; ?>
                        </td>
					</tr>
                    <tr>
                        <td class="sbold">Periodo:</td>
                        <td>
                            <?php echo $participacao->getAtividade()->getEvento()->getPeriodo(); ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="sbold">Edição:</td>
                        <td>
                            <?php echo $participacao->getAtividade()->getEvento()->getNumeroEdicao(); ?>
                        </td>
                    </tr>


					<tr>
						<td class="sbold">Chave de validação:</td>
						<td><?php echo $this->certificadoFormat($participacao->getChaveValidacao()); ?></td>
					</tr>
					<tr>
						<td class="sbold">Função:</td>
						<td><?php echo $participacao->getFuncao(); ?></td>
					</tr>
					<tr>
						<td class="sbold">Tipo da atividade:</td>
						<td><?php echo $participacao->getAtividade()->getTipoAtividade(); ?></td>
					</tr>
					<tr>
						<td class="sbold">Atividade:</td>
						<td><?php echo $participacao->getAtividade(); ?></td>
					</tr>
					<tr>
						<td class="sbold">Carga horária:</td>
                        <td>
                            <?php if($participacao->getCargaHoraria() == 0): ?>
                                ----
                            <?php else: ?>
                                <?php echo $participacao->getCargaHoraria(); ?> <?php echo ($participacao->getCargaHoraria() > 1) ? 'horas' : 'hora'; ?>
                            <?php endif; ?>

                        </td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>

    <div class="page-footer" style="bottom: 0;width: 100%;padding: 20px;background: #565353;color: #fff; margin: 0 !important;">
        <h5 class="text-center" style="font-weight: 600;">
            Dúvidas ou problemas
            ? certificados.vdc@ifba.edu.br
        </h5>
    </div>

<?php else: ?>
    <!-- BEGIN LOGIN -->
	<div class="content" style="margin-top: 40px; width: 450px;">
		<!-- BEGIN LOGO -->
		<div style="padding: 20px 0">
			<a href="/emitir"> <img src="/assets/layouts/layout4/img/logo.png" alt="" class="center-block" /></a>
		</div>
		<!-- END LOGO -->

        <?php if($this->menssages):?>
            <div class="alert alert-danger alert-bold-border fade in alert-dismissable">
				<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <?php echo $this->menssages; ?>
            </div>
        <?php endif; ?>

        <!-- BEGIN LOGIN FORM -->
        <?php echo $this->form()->openTag($this->form);?>



        <div class="form-group <?php if($this->formElementErrors($this->form->get('chave'))) echo " has-error" ?>">
			<!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
			<label class="control-label visible-ie8 visible-ie9">Chave</label>

            <?php echo $this->formElement($this->form->get('chave')); ?>

            <?php
            if ($this->formElementErrors($this->form->get('chave')))
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small data-bv-validator="notEmpty" class="help-block" style="">')
                    ->setMessageSeparatorString('</small><small data-bv-validator="notEmpty" class="help-block" style="">')
                    ->setMessageCloseString('</small>')
                    ->render($this->form->get('chave'));
            ?>
        </div>

        <div class="form-group <?php if($this->formElementErrors($this->form->get('captcha'))) echo " has-error" ?>">

            <?php echo $this->formElement($this->form->get('captcha')); ?>

            <?php
            if ($this->formElementErrors($this->form->get('captcha')))
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small data-bv-validator="notEmpty" class="help-block" style="">')
                    ->setMessageSeparatorString('</small><small data-bv-validator="notEmpty" class="help-block" style="">')
                    ->setMessageCloseString('</small>')
                    ->render($this->form->get('captcha'));
            ?>
        </div>

		<div class="form-actions" style="border-bottom: 0;">
			<button type="submit" class="btn green btn-block"
				id="btn-buscar-certificados" style="padding: 8px 0;">Verificar</button>
		</div>
		<!-- END LOGIN FORM -->
	</div>
	<!-- END LOGIN -->

    <div class="page-footer" style="position: absolute;bottom: 0;width: 100%;padding: 20px;background: #565353;color: #fff; margin: 0 !important;">
        <h5 class="text-center" style="font-weight: 600;">
            Dúvidas ou problemas
            ? certificados.vdc@ifba.edu.br
        </h5>
    </div>
<?php endif; ?>






	<!--[if lt IE 9]>
<script src="/assets/global/plugins/respond.min.js"></script>
<script src="/assets/global/plugins/excanvas.min.js"></script>
<![endif]-->
	<!-- BEGIN CORE PLUGINS -->
	<script src="/assets/global/plugins/jquery.min.js"
		type="text/javascript"></script>
	<script src="/assets/global/plugins/bootstrap/js/bootstrap.min.js"
		type="text/javascript"></script>
	<script src="/assets/global/plugins/js.cookie.min.js"
		type="text/javascript"></script>
	<script
		src="/assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js"
		type="text/javascript"></script>
	<script
		src="/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js"
		type="text/javascript"></script>
	<script src="/assets/global/plugins/jquery.blockui.min.js"
		type="text/javascript"></script>
	<script src="/assets/global/plugins/uniform/jquery.uniform.min.js"
		type="text/javascript"></script>
	<script
		src="/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js"
		type="text/javascript"></script>
	<!-- END CORE PLUGINS -->
	<!-- BEGIN PAGE LEVEL PLUGINS -->
	<script
		src="/assets/global/plugins/jquery-inputmask/jquery.inputmask.bundle.min.js"
		type="text/javascript"></script>
	<script
		src="/assets/global/plugins/jquery.input-ip-address-control-1.0.min.js"
		type="text/javascript"></script>

	<script
		src="/assets/global/plugins/jquery-validation/js/jquery.validate.min.js"
		type="text/javascript"></script>
	<script
		src="/assets/global/plugins/jquery-validation/js/additional-methods.min.js"
		type="text/javascript"></script>
	<script src="/assets/global/plugins/select2/js/select2.full.min.js"
		type="text/javascript"></script>
	<!-- END PAGE LEVEL PLUGINS -->
	<!-- BEGIN THEME GLOBAL SCRIPTS -->
	<script src="/assets/global/scripts/app.min.js" type="text/javascript"></script>
	<!-- END THEME GLOBAL SCRIPTS -->
	<!-- BEGIN PAGE LEVEL SCRIPTS -->
	<script src="/assets/pages/scripts/login.min.js" type="text/javascript"></script>
	<!-- END PAGE LEVEL SCRIPTS -->
	<!-- BEGIN THEME LAYOUT SCRIPTS -->
	<script src="/assets/pages/scripts/form-input-mask.js"
		type="text/javascript"></script>
	<!-- END THEME LAYOUT SCRIPTS -->

	<script type="text/javascript">

    $(window).bind("pageshow", function() {
        $("#chave").val("");
    });

    $(document).ready(function() {
        $("#chave").inputmask("****-****-****-****");
    });

</script>
</body>

</html>